apiVersion: apps/v1
kind: Deployment
metadata:
  name: angular-cd
  labels:
    app: angular
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yashkalabel
  template:
    metadata:
      labels:
        app: yashkalabel
    spec:
      containers:
      - name: angularapp
        image: ykum01/angular-image:1.0.0
        ports:
        - containerPort: 80
        imagePullPolicy: Always
