---
kind: Deployment
apiVersion: apps/v1
metadata:
   name: mydeployment
spec:
   replicas: 1
   selector:
       matchLabels:
          name: deployment1
   template:
       metadata:
         name: uideployment
         labels:
            name: deployment1
       spec:
          containers:
             - name: angularcontanier
               image: bhasmeht/angular-image # {"$imagepolicy": "flux-system:mypolicy"}
               ports:
                  - containerPort: 80
               imagePullPolicy: Always 

---
kind: Deployment
apiVersion: apps/v1
metadata:
   name: mydeploymenttest
spec:
   replicas: 1
   selector:
       matchLabels:
          name: deployment
   template:
       metadata:
         name: testdeployment
         labels:
            name: deployment
       spec:
          containers:
             - name: testdeployment
               image: nginx
               ports:
                  - containerPort: 80
               imagePullPolicy: Always                