apiVersion: image.toolkit.fluxcd.io/v1alpha1
kind: ImageUpdateAutomation
metadata:
  name: flux-system
  namespace: flux-system
spec:
  checkout:
    branch: main
    gitRepositoryRef:
      name: flux-system
  commit:
    authorEmail: bhaskarmehta422@gmail.com
    authorName: bhaskarmehta
    messageTemplate: 'update image'    
  interval: 1m0s
  push:  
    branch: main
  update:
    path: .
    strategy: Setters 