apiVersion: v1
kind: Service
metadata:
     name: myangularservice
spec:
   selector:
       name: yashkalabel
   ports:
     - protocol: "TCP"
       port: 80
       targetPort: 80 
   type: NodePort